### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by erankor** [hltbra/strftime-nginx-module#5]
Hi,

First of all, thanks for this module.
I want to use this module and noticed it doesn't have a license file, is it possible to add one?
Most nginx modules use http://nginx.org/LICENSE, I will happily submit a pull for that if you agree.

Thank you,

Eran

**Comment by hltbra** [comment]
I added the MIT license to the LICENSE file (https://github.com/hltbra/strftime-nginx-module/commit/013cd37a92411302785cd4501c0766013548b09c). Thanks for creating this ticket, @erankor.

**Comment by erankor** [comment]
Thanks @hltbra !
